import { cardArtwork } from './art.js';
let socket, state=null, seat=null, selected=null, room=null;
const $=id=>document.getElementById(id); const ids=['hand','playerBoard','enemyBoard','playerShields','enemyShields','playerRunes','enemyRunes','playerMeta','enemyMeta','playerName','enemyName','turnPill','selectedName','selectedText','actions','log','endTurnBtn','toast','connection','roomInfo','roomCode','nameInput','roomInput','createRoom','joinRoom']; const els=Object.fromEntries(ids.map(id=>[id,$(id)]));
function connect(){if(location.protocol==='file:'){els.connection.textContent='Az online módhoz indítsd el a szervert: npm start';els.createRoom.disabled=true;els.joinRoom.disabled=true;return;}const proto=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${proto}://${location.host}/ws`);socket.onopen=()=>els.connection.textContent='Szerver elérhető.';socket.onclose=()=>{els.connection.textContent='Kapcsolat megszakadt.';toast('A szerverkapcsolat megszakadt.');};socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='room'){room=m.code;seat=m.seat;els.roomInfo.hidden=false;els.roomCode.textContent=room;els.connection.textContent=m.waiting?'Várakozás a második játékosra…':'Párbaj indul.';}if(m.type==='state'){state=m.state;seat=m.seat;els.connection.textContent='Online párbaj aktív.';render();}if(m.type==='error')toast(m.message);};}
function send(type,payload={}){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type,...payload}));}
function cardEl(card,zone,owner){const el=document.createElement('button');el.type='button';el.className=`card ${card.type} ${card.exhausted&&zone==='board'?'exhausted':''} ${selected?.uid===card.uid?'selected':''}`;el.dataset.rarity=card.rarity;el.innerHTML=`<div class="card-top"><span class="cost">${card.cost}</span><span class="card-name">${card.name}</span></div><div class="art">${cardArtwork(card.id)}</div><div class="card-text">${card.text}</div>${card.type==='creature'?`<div class="stats"><span class="atk">⚔ ${card.atk+card.bonusAtk}</span><span class="hp">♥ ${Math.max(0,card.hp-card.damage)}</span></div>`:''}<i class="rarity-gem"></i>`;el.onclick=()=>{selected={...card,zone,owner};render()};return el;}
function shields(el,n){el.innerHTML='';for(let i=0;i<5;i++){const x=document.createElement('i');x.className=`shield ${i>=n?'broken':''}`;el.appendChild(x)}}function runes(el,p){el.textContent=`RÚNA ${p.runes.filter(r=>!r.used).length} / ${p.runes.length}`}
function button(label,cls,action){const b=document.createElement('button');b.type='button';b.className=`action-btn ${cls||''}`;b.textContent=label;b.onclick=()=>send('action',action);return b}
function render(){if(!state)return;const me=state.players[seat],enemy=state.players[1-seat];els.playerName.textContent=me.name;els.enemyName.textContent=enemy.name;els.hand.replaceChildren(...me.hand.map(c=>cardEl(c,'hand',seat)));els.playerBoard.replaceChildren(...me.board.map(c=>cardEl(c,'board',seat)));els.enemyBoard.replaceChildren(...enemy.board.map(c=>cardEl(c,'board',1-seat)));shields(els.playerShields,me.shields);shields(els.enemyShields,enemy.shields);runes(els.playerRunes,me);runes(els.enemyRunes,enemy);els.playerMeta.textContent=`${me.hand.length} kézlap · ${me.deckCount} pakli`;els.enemyMeta.textContent=`${enemy.handCount} kézlap · ${enemy.deckCount} pakli`;els.turnPill.textContent=state.winner!==null?`${state.players[state.winner].name} győzött`:`${state.turn}. kör · ${state.active===seat?'TE JÖSSZ':'ELLENFÉL'}`;els.endTurnBtn.disabled=state.active!==seat||state.winner!==null;els.log.innerHTML=state.log.slice(0,5).map(x=>`<span>${x}</span>`).join('');renderActions();if(state.winner!==null)toast(`${state.players[state.winner].name} megnyerte a párbajt.`)}
function renderActions(){els.actions.innerHTML='';if(!selected){els.selectedName.textContent='Nincs kiválasztott lap';els.selectedText.textContent='Válassz egy lapot a kezedből vagy egy támadásra kész lényt.';return}els.selectedName.textContent=selected.name;els.selectedText.textContent=selected.text;if(!state||state.active!==seat||state.winner!==null)return;const me=state.players[seat],enemy=state.players[1-seat];if(selected.zone==='hand'&&selected.owner===seat){const live=me.hand.find(c=>c.uid===selected.uid);if(!live)return;if(!me.runePlayed)els.actions.append(button('RÚNÁVÁ TESZEM','',{kind:'rune',uid:live.uid}));const avail=me.runes.filter(r=>!r.used).length;const cost=Math.max(0,live.cost-(live.type==='creature'?me.discount:0));if(avail>=cost)els.actions.append(button(`KIJÁTSZOM · ${cost} RÚNA`,'primary',{kind:'play',uid:live.uid}))}if(selected.zone==='board'&&selected.owner===seat){const live=me.board.find(c=>c.uid===selected.uid);if(!live||live.exhausted)return;els.actions.append(button(enemy.shields>0?'ŐRKŐ TÁMADÁSA':'MAG TÁMADÁSA','warn',{kind:'attack',uid:live.uid,target:null}));enemy.board.forEach(t=>els.actions.append(button(`↳ ${t.name}`,'',{kind:'attack',uid:live.uid,target:t.uid})))} }
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2000)}
els.createRoom.onclick=()=>send('create',{name:els.nameInput.value.trim()||'Rúnaidéző'});els.joinRoom.onclick=()=>send('join',{code:els.roomInput.value.trim().toUpperCase(),name:els.nameInput.value.trim()||'Vendég'});els.endTurnBtn.onclick=()=>{selected=null;send('action',{kind:'end'})};window.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;render()}});connect();
