import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {createGame,placeRune,playCard,attack,endTurn} from './engine.js';
const root=path.dirname(fileURLToPath(import.meta.url));const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};const publicFiles=new Set(['/online.html','/online.js','/styles.css','/art.js','/index.html']);
const server=http.createServer((req,res)=>{let raw;try{raw=decodeURIComponent((req.url||'/').split('?')[0])}catch{res.writeHead(400);return res.end('Bad request')}if(raw==='/health'){res.writeHead(200,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});return res.end(JSON.stringify({ok:true}))}const p=raw==='/'?'/online.html':raw==='/ai'?'/index.html':raw;if(!publicFiles.has(p)){res.writeHead(404);return res.end('Not found')}const full=path.join(root,p);fs.readFile(full,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime[path.extname(full)]||'application/octet-stream','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(data)})});
class Peer{constructor(socket){this.socket=socket;this.buffer=Buffer.alloc(0);this.room=null;this.seat=null;socket.on('data',d=>this.onData(d));socket.on('close',()=>leave(this));socket.on('error',()=>leave(this))}send(obj){if(this.socket.destroyed)return;const data=Buffer.from(JSON.stringify(obj));let head;if(data.length<126){head=Buffer.from([0x81,data.length])}else if(data.length<65536){head=Buffer.alloc(4);head[0]=0x81;head[1]=126;head.writeUInt16BE(data.length,2)}else{return}this.socket.write(Buffer.concat([head,data]))}onData(d){this.buffer=Buffer.concat([this.buffer,d]);while(this.buffer.length>=2){const b1=this.buffer[0],b2=this.buffer[1],opcode=b1&15,masked=!!(b2&128);let len=b2&127,off=2;if(len===126){if(this.buffer.length<4)return;len=this.buffer.readUInt16BE(2);off=4}if(len===127)return this.socket.destroy();const need=off+(masked?4:0)+len;if(this.buffer.length<need)return;if(opcode===8){this.socket.end();return}if(opcode!==1){this.buffer=this.buffer.subarray(need);continue}let payload;if(masked){const mask=this.buffer.subarray(off,off+4);off+=4;payload=Buffer.from(this.buffer.subarray(off,off+len));for(let i=0;i<payload.length;i++)payload[i]^=mask[i%4]}else payload=this.buffer.subarray(off,off+len);this.buffer=this.buffer.subarray(need);try{handle(this,JSON.parse(payload.toString('utf8')))}catch{this.send({type:'error',message:'Hibás üzenet.'})}}}}
const rooms=new Map();const code=()=>{const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let out='';do{out='';for(let i=0;i<5;i++)out+=chars[Math.floor(Math.random()*chars.length)]}while(rooms.has(out));return out};const safeName=x=>String(x||'Játékos').replace(/[<>]/g,'').trim().slice(0,24)||'Játékos';
function view(game,seat){return {active:game.active,turn:game.turn,winner:game.winner,log:game.log,players:game.players.map((p,i)=>({name:p.name,hand:i===seat?p.hand:[],handCount:p.hand.length,board:p.board,runes:p.runes,shields:p.shields,coreOpen:p.coreOpen,runePlayed:p.runePlayed,discount:p.discount,deckCount:p.deck.length}))}}
function broadcast(room){room.peers.forEach((p,i)=>p?.send({type:'state',seat:i,state:view(room.game,i)}))}function leave(peer){const room=peer.room&&rooms.get(peer.room);if(!room)return;room.peers[peer.seat]=null;peer.room=null;if(room.peers.every(x=>!x))rooms.delete(room.code);else room.peers.filter(Boolean).forEach(p=>p.send({type:'error',message:'Az ellenfél lekapcsolódott.'}))}
function handle(peer,m){if(m.type==='create'){leave(peer);const c=code(),name=safeName(m.name);const room={code:c,names:[name,null],peers:[peer,null],game:null};rooms.set(c,room);peer.room=c;peer.seat=0;return peer.send({type:'room',code:c,seat:0,waiting:true})}if(m.type==='join'){leave(peer);const c=String(m.code||'').toUpperCase(),room=rooms.get(c);if(!room||room.peers[1])return peer.send({type:'error',message:'Nincs ilyen szoba, vagy már megtelt.'});room.names[1]=safeName(m.name);room.peers[1]=peer;peer.room=c;peer.seat=1;room.game=createGame(Math.random,room.names);room.peers[0].send({type:'room',code:c,seat:0,waiting:false});peer.send({type:'room',code:c,seat:1,waiting:false});return broadcast(room)}if(m.type==='action'){const room=rooms.get(peer.room);if(!room?.game)return peer.send({type:'error',message:'A párbaj még nem indult el.'});const i=peer.seat;let ok=false;if(m.kind==='rune')ok=placeRune(room.game,i,m.uid);if(m.kind==='play')ok=playCard(room.game,i,m.uid);if(m.kind==='attack')ok=attack(room.game,i,m.uid,m.target??null);if(m.kind==='end')ok=endTurn(room.game);if(!ok)return peer.send({type:'error',message:'Ez a lépés most nem szabályos.'});broadcast(room)}}
server.on('upgrade',(req,socket)=>{if(req.url!='/ws')return socket.destroy();const key=req.headers['sec-websocket-key'];if(!key)return socket.destroy();const accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');new Peer(socket)});
const port=Number(process.env.PORT)||8080;const host='0.0.0.0';server.listen(port,host,()=>console.log(`Runaharc online: http://${host}:${port}`));
