import test from 'node:test';
import assert from 'node:assert/strict';
import {
  CARD_LIBRARY, PRESET_DECKS, DEFAULT_DECK_LIST, DECK_SIZE, MAX_COPIES, MAX_DECK_ELEMENTS,
  GUARDIAN_MAX_HP, CORE_MAX_HP, MAX_RUNES, validateDeckList, createGame, makeCard,
  placeRune, playCard, attack, moveCard, endTurn, availableRunes, openLanes
} from '../engine.js';

const rng=()=>0.42;
const ready=(card,lane=0)=>{card.exhausted=false;card.lane=lane;return card};
const giveRunes=(p,n)=>{p.runes=Array.from({length:n},(_,i)=>({uid:`r${i}`,id:'liderc',name:'Mocsári Lidérc',used:false}))};

// Core state / deck rules
test('new game uses one shared guardian pool, a 10 HP core and second-player catch-up',()=>{const g=createGame(rng);for(const p of g.players){assert.equal(p.guardianHp,GUARDIAN_MAX_HP);assert.equal(p.coreHp,CORE_MAX_HP);assert.equal(p.coreOpen,false)}assert.equal(g.players[0].hand.length,5);assert.equal(g.players[0].deck.length,DECK_SIZE-5);assert.equal(g.players[0].spark,false);assert.equal(g.players[1].hand.length,6);assert.equal(g.players[1].deck.length,DECK_SIZE-6);assert.equal(g.players[1].spark,true)});
test('all preset decks are legal 30-card decks',()=>{for(const [key,preset] of Object.entries(PRESET_DECKS)){const v=validateDeckList(preset.cards);assert.equal(v.ok,true,`${key}: ${v.errors.join('; ')}`);assert.equal(preset.cards.length,DECK_SIZE)}});
test('deck validation enforces exact size, copy cap and two non-neutral elements',()=>{assert.equal(validateDeckList(DEFAULT_DECK_LIST.slice(0,29)).ok,false);assert.equal(validateDeckList([...DEFAULT_DECK_LIST.slice(0,27),'turul','turul','turul']).counts.turul<=MAX_COPIES,false);const invalid=Array(3).fill(['turul','vasorr','bastya','liderc','betyar','kobzos','zivatar','parazs','rovaskor','vereshold']).flat();const v=validateDeckList(invalid);assert.equal(v.ok,false);assert.ok(v.elements.length>MAX_DECK_ELEMENTS)});
test('neutral cards do not consume an element slot',()=>{const deck=Array(3).fill(['turul','zivatar','villamvadasz','vasorr','parazs','betoro','betyar','kobzos','hamufonix','mennydorges']).flat();const v=validateDeckList(deck);assert.equal(v.ok,true,v.errors.join('; '));assert.deepEqual(new Set(v.elements),new Set(['vihar','tuz']))});

// Resource economy
test('rune placement is once per turn and spends a hand card',()=>{const g=createGame(rng),p=g.players[0],n=p.hand.length,u=p.hand[0].uid;assert.equal(placeRune(g,0,u),true);assert.equal(p.hand.length,n-1);assert.equal(p.runes.length,1);assert.equal(placeRune(g,0,p.hand[0].uid),false)});
test('Kezdőszikra is temporary, counts as one rune and expires after the second player first turn',()=>{const g=createGame(rng);const p=g.players[1];assert.equal(availableRunes(p),1);g.active=1;const before=p.spark;assert.equal(before,true);assert.equal(endTurn(g,1),true);assert.equal(p.spark,false);assert.equal(availableRunes(p),0)});
test('Rúnavisszhang draws when third or later rune leaves a small hand',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,2);p.hand=[makeCard('liderc'),makeCard('turul'),makeCard('betyar'),makeCard('kobzos')];const before=p.deck.length;assert.equal(placeRune(g,0,p.hand[0].uid),true);assert.equal(p.runes.length,3);assert.equal(p.hand.length,4);assert.equal(p.deck.length,before-1);assert.equal(g.lastEvent.runeEcho,true)});
test('runes stop at the seven-rune cap',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,MAX_RUNES);assert.equal(placeRune(g,0,p.hand[0].uid),false)});
test('runes refresh on next own turn',()=>{const g=createGame(rng),p=g.players[0];placeRune(g,0,p.hand[0].uid);p.runes[0].used=true;endTurn(g);endTurn(g);assert.equal(availableRunes(p),1)});

// Lane rules + shared guardian pool
test('summoning requires one of five empty lanes',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,2);const c=makeCard('turul');p.hand=[c];assert.equal(playCard(g,0,c.uid),false);assert.equal(playCard(g,0,c.uid,5),false);assert.equal(playCard(g,0,c.uid,2),true);assert.equal(p.board[0].lane,2)});
test('cannot summon onto an occupied lane',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,4);const a=ready(makeCard('liderc'),1),b=makeCard('turul');p.board=[a];p.hand=[b];assert.equal(playCard(g,0,b.uid,1),false);assert.ok(openLanes(p).includes(0));assert.ok(!openLanes(p).includes(1))});
test('creature can attack only the opposing lane blocker',()=>{const g=createGame(rng),a=ready(makeCard('turul'),2),wrong=ready(makeCard('liderc'),1),right=ready(makeCard('liderc'),2);g.players[0].board=[a];g.players[1].board=[wrong,right];assert.equal(attack(g,0,a.uid,wrong.uid),false);assert.equal(a.exhausted,false);assert.equal(attack(g,0,a.uid,right.uid),true)});
test('ordinary creature cannot hit shared guardian life through a blocker',()=>{const g=createGame(rng),a=ready(makeCard('turul'),2),b=ready(makeCard('bastya'),2);g.players[0].board=[a];g.players[1].board=[b];assert.equal(attack(g,0,a.uid),false);assert.equal(g.players[1].guardianHp,GUARDIAN_MAX_HP);assert.equal(a.exhausted,false)});
test('open attacks from different lanes damage the same shared guardian pool',()=>{const g=createGame(rng),a=ready(makeCard('turul'),0),b=ready(makeCard('betyar'),4);b.bonusAtk=0;g.players[0].board=[a,b];assert.equal(attack(g,0,a.uid),true);assert.equal(g.players[1].guardianHp,18);assert.equal(attack(g,0,b.uid),true);assert.equal(g.players[1].guardianHp,15)});
test('guardian collapse never overflows excess attack damage into the core',()=>{const g=createGame(rng),a=ready(makeCard('sarkany'),1);g.players[0].board=[a];g.players[1].guardianHp=2;assert.equal(attack(g,0,a.uid),true);assert.equal(g.players[1].guardianHp,0);assert.equal(g.players[1].coreOpen,true);assert.equal(g.players[1].coreHp,CORE_MAX_HP)});
test('after guardian collapse any open lane can damage the core',()=>{const g=createGame(rng),a=ready(makeCard('betyar'),4);g.players[0].board=[a];g.players[1].guardianHp=0;g.players[1].coreOpen=true;assert.equal(attack(g,0,a.uid),true);assert.equal(g.players[1].coreHp,7)});
test('a blocker still protects the core after the shared guardian pool collapses',()=>{const g=createGame(rng),a=ready(makeCard('turul'),1),b=ready(makeCard('liderc'),1);g.players[0].board=[a];g.players[1].board=[b];g.players[1].guardianHp=0;g.players[1].coreOpen=true;assert.equal(attack(g,0,a.uid),false);assert.equal(g.players[1].coreHp,CORE_MAX_HP)});
test('Széljáró bypasses a blocker only while guardian life remains',()=>{const g=createGame(rng),a=ready(makeCard('szellovas'),3),b=ready(makeCard('bastya'),3);g.players[0].board=[a];g.players[1].board=[b];assert.equal(attack(g,0,a.uid),true);assert.equal(g.players[1].guardianHp,18);a.exhausted=false;g.players[1].guardianHp=0;g.players[1].coreOpen=true;assert.equal(attack(g,0,a.uid),false);assert.equal(g.players[1].coreHp,10)});
test('Élő Kőfal reduces shared guardian damage from creature attacks by one, non-stacking',()=>{const g=createGame(rng),a=ready(makeCard('betyar'),0);a.bonusAtk=0;g.players[0].board=[a];g.players[1].board=[ready(makeCard('kofal'),1),ready(makeCard('kofal'),2)];assert.equal(attack(g,0,a.uid),true);assert.equal(g.players[1].guardianHp,18);assert.equal(g.lastEvent.guardianBlocked,1)});
test('Rovásbástya remains passive and cannot attack',()=>{const g=createGame(rng),b=ready(makeCard('bastya'),0);g.players[0].board=[b];assert.equal(attack(g,0,b.uid),false);assert.equal(b.exhausted,false)});

// Direct damage / healing / card mechanics
test('Kőrepesztés damages shared guardian life directly through blockers',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,2);const s=makeCard('korepesztes');p.hand=[s];g.players[1].board=[ready(makeCard('kofal'),0)];assert.equal(playCard(g,0,s.uid),true);assert.equal(g.players[1].guardianHp,17)});
test('Lángostrom deals four to guardian life but cannot damage an already open core',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,4);let s=makeCard('langostrom');p.hand=[s];assert.equal(playCard(g,0,s.uid),true);assert.equal(g.players[1].guardianHp,16);p.runes.forEach(r=>r.used=false);s=makeCard('langostrom');p.hand=[s];g.players[1].guardianHp=0;g.players[1].coreOpen=true;assert.equal(playCard(g,0,s.uid),true);assert.equal(g.players[1].coreHp,10)});
test('Őrkőkovács repairs the shared guardian pool but cannot revive it from zero',()=>{const g=createGame(rng),p=g.players[0];p.guardianHp=15;giveRunes(p,3);let c=makeCard('orkokovac');p.hand=[c];assert.equal(playCard(g,0,c.uid,0),true);assert.equal(p.guardianHp,18);p.runes.forEach(r=>r.used=false);p.guardianHp=0;p.coreOpen=true;c=makeCard('orkokovac');p.hand=[c];assert.equal(playCard(g,0,c.uid,1),true);assert.equal(p.guardianHp,0)});
test('Áradás heals four guardian life and draws only on a meaningful heal',()=>{const g=createGame(rng),p=g.players[0];p.guardianHp=14;giveRunes(p,3);const before=p.deck.length,s=makeCard('aradas');p.hand=[s];assert.equal(playCard(g,0,s.uid),true);assert.equal(p.guardianHp,18);assert.equal(p.deck.length,before-1)});
test('Mennydörgés hits every enemy creature and draws if at least two were hit',()=>{const g=createGame(rng),p=g.players[0],e=g.players[1];giveRunes(p,4);e.board=[ready(makeCard('bastya'),0),ready(makeCard('turul'),2)];const before=p.deck.length,s=makeCard('mennydorges');p.hand=[s];assert.equal(playCard(g,0,s.uid),true);assert.equal(e.board[0].damage,1);assert.equal(e.board[1].damage,1);assert.equal(p.deck.length,before-1)});
test('Hamufőnix returns to hand once after dying',()=>{const g=createGame(rng),phoenix=ready(makeCard('hamufonix'),0),killer=ready(makeCard('foldrengeto'),0);g.players[0].board=[killer];g.players[1].board=[phoenix];assert.equal(attack(g,0,killer.uid,phoenix.uid),true);const reborn=g.players[1].hand.find(c=>c.id==='hamufonix');assert.ok(reborn);assert.equal(reborn.reborn,true)});
test('Lidércsereg receives +1/+1 after two own deaths',()=>{const g=createGame(rng),p=g.players[0];p.deaths=2;giveRunes(p,3);const c=makeCard('lidercsapat');p.hand=[c];assert.equal(playCard(g,0,c.uid,0),true);assert.equal(c.atk,3);assert.equal(c.hp,4)});
test('Ősök Hangja restores the oldest rune and draws one card',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,3);p.runes[0]={uid:'x',id:'turul',name:'Turul Őrszem',used:false};const s=makeCard('osokhangja');p.hand=[s];const before=p.deck.length;assert.equal(playCard(g,0,s.uid),true);assert.equal(p.runes.length,2);assert.ok(p.hand.some(c=>c.id==='turul'));assert.equal(p.deck.length,before-1)});
test('Csodaszarvas can move once to an adjacent empty lane before attacking',()=>{const g=createGame(rng),c=ready(makeCard('csodaszarvas'),2);g.players[0].board=[c];assert.equal(moveCard(g,0,c.uid,3),true);assert.equal(c.lane,3);assert.equal(moveCard(g,0,c.uid,4),false)});

// No-draw terminal behavior
test('fatigue escalates 1, 2, 3... directly against the core',()=>{const g=createGame(rng);g.players[0].deck=[];g.players[1].deck=[];assert.equal(endTurn(g,0),true);assert.equal(g.players[1].fatigue,1);assert.equal(g.players[1].coreHp,9);assert.equal(endTurn(g,1),true);assert.equal(g.players[0].fatigue,1);assert.equal(g.players[0].coreHp,9);assert.equal(endTurn(g,0),true);assert.equal(g.players[1].fatigue,2);assert.equal(g.players[1].coreHp,7)});
test('empty decks always produce a winner within seven end-turns, never a draw',()=>{const g=createGame(rng);for(const p of g.players){p.deck=[];p.hand=[];p.board=[];p.coreHp=10}let n=0;while(g.winner===null&&n<10){assert.equal(endTurn(g,g.active),true);n++}assert.ok(g.winner===0||g.winner===1);assert.ok(n<=7)});
test('invalid attack target does not consume the attacker action',()=>{const g=createGame(rng),a=ready(makeCard('turul'),0);g.players[0].board=[a];assert.equal(attack(g,0,a.uid,'missing'),false);assert.equal(a.exhausted,false)});
test('endTurn rejects the non-active player',()=>{const g=createGame(rng);const before=g.players[0].hand.length;assert.equal(endTurn(g,1),false);assert.equal(g.active,0);assert.equal(g.players[0].hand.length,before)});
test('spell event exposes readable card information to clients',()=>{const g=createGame(rng),p=g.players[0];giveRunes(p,2);const s=makeCard('forras');p.hand=[s];assert.equal(playCard(g,0,s.uid),true);assert.equal(g.lastEvent.type,'spell');assert.equal(g.lastEvent.cardName,'Ősforrás');assert.match(g.lastEvent.cardText,/Húzz 1 lapot/)});
