import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=f=>fs.readFileSync(new URL(`../${f}`,import.meta.url),'utf8');

for(const file of ['online.html','index.source.html']){
  test(`${file}: action panel stays between arena and hand`,()=>{const html=read(file);const arenaEnd=html.indexOf('</section>',html.indexOf('class="arena"'));const action=html.indexOf('id="actionPanel"');const hand=html.indexOf('class="hand-panel"');assert.ok(arenaEnd>=0&&action>arenaEnd&&hand>action)});
  test(`${file}: sound toggle and spell reveal exist`,()=>{const html=read(file);assert.match(html,/id="soundBtn"/);assert.match(html,/aria-pressed="true"/);assert.match(html,/id="spellReveal"/)});
  test(`${file}: deck builder is reachable from the top bar`,()=>{assert.match(read(file),/href="\/?deckbuilder\.html"[^>]*>PAKLIÉPÍTŐ</)});
}

test('compact cards keep names and attack values explicitly white',()=>{const css=read('styles.css');assert.match(css,/\.card-name\{[^}]*color:#fff!important/);assert.match(css,/\.stats \.atk\{[^}]*color:#fff!important/)});
test('battlefield still exposes five centered lanes',()=>{const css=read('styles.css'),game=read('game.js');assert.match(css,/grid-template-columns:repeat\(5/);assert.match(css,/\.board-row\{width:min\(1080px,calc\(100% - 28px\)\)/);assert.match(game,/for \(let lane = 0; lane < 5; lane\+\+\)/)});
test('selected-card panel exposes metadata and full rules text',()=>{const html=read('online.html'),js=read('online.js');assert.match(html,/id="selectedMeta"/);assert.match(js,/els\.selectedMeta\.textContent = cardMetaText\(selected\)/);assert.match(js,/els\.selectedText\.textContent = selected\.text/)});
test('selected-card panel is materially larger and more readable on desktop',()=>{const css=read('styles.css');assert.match(css,/grid-template-rows:52px minmax\(0,1fr\) 150px/);assert.match(css,/body\.game-active \.action-copy b\{display:block;font-size:19px/);assert.match(css,/body\.game-active \.selected-meta\{font-size:13.5px/);assert.match(css,/body\.game-active \.action-copy small\{font-size:16px;line-height:1\.5/)});
test('shared guardian UI is one shared HP meter rather than five lane shields',()=>{const js=read('online.js');assert.match(js,/ŐRKŐ-ÉLET <b>\$\{hp\}\/\$\{GUARDIAN_MAX_HP\}<\/b>/);assert.match(js,/enemy\.guardianHp > 0/);assert.doesNotMatch(js,/enemy\.guardians\[/)});
test('attack buttons target shared guardian life or core',()=>{const js=read('online.js');assert.match(js,/ŐRKŐ-ÉLET TÁMADÁSA · \$\{enemy\.guardianHp\}\/\$\{GUARDIAN_MAX_HP\}/);assert.match(js,/MAG MEGTÁMADÁSA · \$\{enemy\.coreHp\}\/\$\{CORE_MAX_HP\} ÉP/)});
test('online client and HTML share version 11 contract',()=>{const html=read('online.html'),js=read('online.js'),server=read('server.js');assert.match(html,/meta name="runaharc-ui" content="11"/);assert.match(js,/expectedUiVersion = '11'/);assert.match(js,/expectedProtocolVersion = 11/);assert.match(server,/protocolVersion:11/);const m=js.match(/const ids = \[([^\]]+)\]/s);assert.ok(m);for(const id of [...m[1].matchAll(/'([^']+)'/g)].map(x=>x[1]))assert.match(html,new RegExp(`id="${id}"`),`missing #${id}`)});
test('online UI counts the second-player Kezdőszikra as temporary available resource',()=>{const js=read('online.js');assert.match(js,/function available\(player\) \{ return player\.runes\.filter\(rune => !rune\.used\)\.length \+ \(player\.spark \? 1 : 0\); \}/);assert.match(js,/\+1 SZIKRA/)});
test('online action lock prevents duplicate actions while awaiting server',()=>{const js=read('online.js');assert.match(js,/let actionPending = false/);assert.match(js,/if \(!uiReady \|\| actionPending \|\| socket\?\.readyState !== WebSocket\.OPEN\) return/);assert.match(js,/actionPending = true/);assert.match(js,/A szerver nem válaszolt időben/)});
test('rules explain shared guardian pool and escalating fatigue',()=>{const html=read('index.source.html');assert.match(html,/20 közös Őrkő-élet/);assert.match(html,/először 1-et, majd 2-t, 3-at/);assert.match(html,/10 életerős Mag/);assert.match(html,/első játékos 5, a második 6 lappal kezd/);assert.match(html,/Kezdőszikrát/)});
test('deck builder exposes presets, filters, collection and save action',()=>{const html=read('deckbuilder.html'),js=read('deckbuilder.js');for(const id of ['deckPresets','elementFilter','collectionGrid','deckList','saveDeck'])assert.match(html,new RegExp(`id="${id}"`));assert.match(js,/PRESET_DECKS/);assert.match(js,/localStorage\.setItem/);assert.match(js,/validateDeckList/)});
test('deck builder CSS remains responsive',()=>{const css=read('styles.css');assert.match(css,/\.deck-workspace\{display:grid;grid-template-columns:340px 1fr/);assert.match(css,/@media\(max-width:1050px\).*\.deck-workspace\{grid-template-columns:1fr\}/s)});
test('new archetype cards all have artwork routing',()=>{const art=read('art.js');for(const id of ['villamvadasz','mennydorges','hamufonix','langostrom','kofal','foldrengeto','forrastunder','aradas','osokhangja','lidercsapat'])assert.match(art,new RegExp(`${id}:`),id)});
test('update bundle includes deck builder and the full online contract',()=>{const build=read('scripts/build-update.mjs');for(const f of ['deckbuilder.html','deckbuilder.js','online.html','online.js','server.js','engine.js','styles.css','balance-report.json','archetype-report.json','element-report.json'])assert.match(build,new RegExp(`'${f.replace('.','\\.')}'`))});
